// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:flutter_bili/feature/login/model/credential_m.dart';
import 'package:flutter_bili/feature/settings/model/settings_m.dart';
import 'package:hive_ce/hive_ce.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CredentialsAdapter());
    registerAdapter(PlayerLibraryAdapter());
    registerAdapter(VideoQualityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CredentialsAdapter());
    registerAdapter(PlayerLibraryAdapter());
    registerAdapter(VideoQualityAdapter());
  }
}
