// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:flutter_bili/feature/login/model/credential_m.dart';
import 'package:flutter_bili/feature/setting/model/setting_m.dart';
import 'package:hive_ce/hive_ce.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CredentialMAdapter());
    registerAdapter(PlayerLibraryMAdapter());
    registerAdapter(SettingMAdapter());
    registerAdapter(VideoQualityMAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CredentialMAdapter());
    registerAdapter(PlayerLibraryMAdapter());
    registerAdapter(SettingMAdapter());
    registerAdapter(VideoQualityMAdapter());
  }
}
