import 'package:hive_ce_flutter/hive_flutter.dart';
import '../models/auth/credentials.dart';

abstract final class AppStorage {
  static late Box<Credentials> credentials;
  static late Box<dynamic> cache;

  static Future<void> init() async {
    await Hive.initFlutter();
    Hive.registerAdapter(CredentialsAdapter()); // generated by build_runner
    credentials = await Hive.openBox<Credentials>('credentials');
    cache = await Hive.openBox<dynamic>('cache');
  }
}
