// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:flutter_bili/login/model/credentials.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CredentialsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CredentialsAdapter());
  }
}
